# pipeline to build simple plugin in go
workspace:
  base: /go

pipeline:
  build:
    image: golang
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      - echo "Some text for plugin" > ./plugin_data.txt
      - ls -la

  publish:
    image: heflik/weather-plugin
    pull: true
    tag: latest
    url: http://samples.openweathermap.org
    api: '/data/2.5/weather?q='
    location: Gliwice
    filename: 'plugin_data.txt'
